customSyntax: postcss-syntax
extends:
  - stylelint-config-recommended
  - stylelint-config-styled-components
plugins:
  - stylelint-config-rational-order/plugin
  - stylelint-order
ignoreFiles:
  - 'node_modules/**/*'
  - 'dist/**/*'
  - '**/*.d.ts'
rules:
  order/properties-order:
    - []
    - unspecified: bottom
      emptyLineMinimumPropertyThreshold: 4

  plugin/rational-order:
    - true
    - empty-line-between-groups: threshold
      empty-line-property-threshold: 3
      empty-lines-within-groups: false
      empty-line-before-unspecified: always
      unspecified: bottomAlphabetical

  block-no-empty: null
  color-hex-case: upper
  declaration-colon-newline-after: null
  declaration-empty-line-before: null
  font-family-name-quotes: always-unless-keyword
  font-family-no-missing-generic-family-keyword: null
  function-comma-newline-after: null
  function-name-case: null
  function-whitespace-after: null
  indentation: 2
  no-empty-first-line: null
  no-eol-whitespace: null
  no-extra-semicolons: null
  no-missing-end-of-source-newline: null
  selector-max-empty-lines: 2
  string-quotes: single
  value-keyword-case: null
  value-list-comma-newline-after: null
