nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: '${FONT_AWESOME_NPM_TOKEN:-}'
    npmRegistryServer: 'https://npm.fontawesome.com'
  gsap:
    npmAlwaysAuth: true
    npmAuthToken: '${GSAP_NPM_TOKEN:-}'
    npmRegistryServer: 'https://npm.greensock.com'
  voxmedia:
    npmAlwaysAuth: true
    npmAuthToken: '${GITHUB_TOKEN:-}'
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
